### ISSUE TITLE
Howcome sds doesn't allow to compile with jemalloc?

### ISSUE THREAD

**Issue by thedrow** [antirez/sds#26]
Am I missing something or support for alternative allocators should be added?

**Comment by kyrias** [comment]
What kind of support should be added? Just compile it against another malloc and it should work just fine.

**Comment by thedrow** [comment]
redis has a header called [zmalloc](https://github.com/antirez/redis/blob/unstable/src/zmalloc.h) which contains macros that allows you to replace the allocator.
SDS doesn't use it.

**Comment by kyrias** [comment]
Which is in no way required to use another malloc implementation?

**Comment by kyrias** [comment]
I mean, you don’t seem to know what zmalloc actually does? It has nothing to do with allocator implementations. If you want to sds to use a different one you just link to a different malloc implentation, like `-ljemalloc` or whatever.
